version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MAVEN_OPTS: "-DskipTests"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
      SPRING_PROFILES_ACTIVE: prod
      ADMIN_USERNAME: newuser
      ADMIN_PASSWORD: newpassword
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  pgdata: