version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farm24
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        MAVEN_OPTS: "-DskipTests"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/farm24
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  pgdata: