CREATE TABLE public."admin" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	login varchar(255) NOT NULL,
	password_hash varchar(255) NULL,
	CONSTRAINT admin_pkey PRIMARY KEY (id),
	CONSTRAINT uk3x1e18lmu2r0xekpql9xme0pp UNIQUE (login)
);

CREATE TABLE public.consumers (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	address varchar(255) NOT NULL,
	"name" varchar(255) NULL,
	phone varchar(255) NOT NULL,
	total_sum int4 NOT NULL,
	CONSTRAINT consumers_pkey PRIMARY KEY (id),
	CONSTRAINT uk5elyp3ggrmvnt2cpeq5wy7mgw UNIQUE (name)
);

CREATE TABLE public.products (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"cost" int4 NOT NULL,
	created_count int4 NOT NULL,
	is_weighed bool NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT products_pkey PRIMARY KEY (id),
	CONSTRAINT uko61fmio5yukmmiqgnxf8pnavn UNIQUE (name)
);

CREATE TABLE public.orders (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	consumer_id int8 NOT NULL,
	"cost" int4 NOT NULL,
	count int4 NOT NULL,
	created_at date NULL,
	product_id int8 NOT NULL,
	status varchar(255) NULL,
	weight float8 NOT NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (id),
	CONSTRAINT orders_status_check CHECK (((status)::text = ANY ((ARRAY['DONE'::character varying, 'DELIVERY'::character varying, 'CREATED'::character varying, 'ARCHIVED'::character varying, 'DELETED'::character varying])::text[]))),
	CONSTRAINT orders_consumer_fk FOREIGN KEY (consumer_id) REFERENCES public.consumers(id) ON DELETE CASCADE,
	CONSTRAINT orders_product_fk FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE
);